#spring.application.name=attack
server:
  port: 8090

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/attack?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql093
  neo4j:
    uri: "bolt://localhost:7687"
    authentication:
      username: neo4j
      password: neo4j093
    encryption:
      enabled: false

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.attack.model

