@startuml
!define RECTANGLE class

skinparam linetype ortho
skinparam componentStyle rectangle
skinparam defaultFontName Arial
skinparam defaultFontSize 14



package "Frontend" {
    component "MyTechManage.vue" as MyTechManage {
        RECTANGLE "Data Properties" as DataProperties {
            - tableData: Array
            - pageSize: Number
            - pageNum: Number
            - total: Number
            - no: String
            - dialogVisible: Boolean
            - form: Object {
                no: String
                ca0: String
                ca1: String
                pa0: String
                pa1: String
                r: String
            }


        RECTANGLE "Methods" as Methods {
            + mod(row)
            + del(id)
            + resetForm()
            + add()
            + doSave()
            + doMod()
            + save()
            + loadPost()
            + resetParam()
            + handleSizeChange(val)
            + handleCurrentChange(val)
            + beforeMount()
        }
    }
}

package "Backend" {
    component "axios" as Axios {
        RECTANGLE "API Endpoints" as API {

        }
    }
}

' Relationships
MyTechManage -> Axios : Uses
MyTechManage ..> DataProperties : Contains
MyTechManage ..> Methods : Contains
Axios ..> API : Contains


@enduml